/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run `npm run images` after changing anything in public/images.
 *
 * Carries real intrinsic dimensions so components can reserve layout space and
 * avoid cumulative layout shift.
 */
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  srcSet: string;
};

export const images = {
  "arch": {
    "src": "/images/arch.webp",
    "width": 1600,
    "height": 1200,
    "srcSet": "/images/arch-640.webp 640w, /images/arch-1024.webp 1024w, /images/arch-1600.webp 1600w"
  },
  "engine": {
    "src": "/images/engine.webp",
    "width": 1600,
    "height": 1067,
    "srcSet": "/images/engine-640.webp 640w, /images/engine-1024.webp 1024w, /images/engine-1600.webp 1600w"
  },
  "hero-bg": {
    "src": "/images/hero-bg.webp",
    "width": 1600,
    "height": 2400,
    "srcSet": "/images/hero-bg-640.webp 640w, /images/hero-bg-1024.webp 1024w, /images/hero-bg-1600.webp 1600w"
  },
  "sarah-desk": {
    "src": "/images/sarah-desk.webp",
    "width": 1600,
    "height": 2400,
    "srcSet": "/images/sarah-desk-640.webp 640w, /images/sarah-desk-1024.webp 1024w, /images/sarah-desk-1600.webp 1600w"
  },
  "sarah": {
    "src": "/images/sarah.webp",
    "width": 1600,
    "height": 2400,
    "srcSet": "/images/sarah-640.webp 640w, /images/sarah-1024.webp 1024w, /images/sarah-1600.webp 1600w"
  },
  "studio": {
    "src": "/images/studio.webp",
    "width": 1600,
    "height": 1205,
    "srcSet": "/images/studio-640.webp 640w, /images/studio-1024.webp 1024w, /images/studio-1600.webp 1600w"
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageName = keyof typeof images;
