/**
 * Image pipeline.
 *
 * Static export disables Next's image optimizer, so the raw JPEGs in
 * public/images were being shipped as-is — 1.8MB total, no modern formats, and
 * no intrinsic dimensions in the markup (which causes layout shift).
 *
 * For each source image this writes:
 *   <name>-<width>.webp  responsive widths, for srcset
 *   <name>.webp          the largest width, as the plain fallback
 * and emits src/lib/images.ts with real dimensions so components can set
 * width/height and reserve space before the image loads.
 *
 * Deterministic and idempotent: `npm run images`.
 */
import sharp from "sharp";
import { readdir, writeFile, mkdir, stat } from "node:fs/promises";
import path from "node:path";

// Sources live outside public/ so the originals are never deployed -- only the
// generated WebP is served. Keeps ~1.8MB of unused JPEG out of every build.
const SRC_DIR = "assets/images";
const OUT_DIR = "public/images";
const WIDTHS = [640, 1024, 1600];
const QUALITY = 74;

const files = (await readdir(SRC_DIR)).filter((f) => /\.(jpe?g|png)$/i.test(f));
if (files.length === 0) {
  console.log("no source images found");
  process.exit(0);
}

await mkdir(OUT_DIR, { recursive: true });

const manifest = {};
let before = 0;
let after = 0;

for (const file of files) {
  const abs = path.join(SRC_DIR, file);
  const name = file.replace(/\.[^.]+$/, "");
  before += (await stat(abs)).size;

  const image = sharp(abs);
  const meta = await image.metadata();
  const srcW = meta.width ?? 0;
  const srcH = meta.height ?? 0;

  // Never upscale: only emit widths the source can actually supply.
  const widths = WIDTHS.filter((w) => w <= srcW);
  if (widths.length === 0) widths.push(srcW);

  const variants = [];
  for (const w of widths) {
    const out = path.join(OUT_DIR, `${name}-${w}.webp`);
    await sharp(abs).resize({ width: w }).webp({ quality: QUALITY }).toFile(out);
    after += (await stat(out)).size;
    variants.push({ width: w, src: `/images/${name}-${w}.webp` });
  }

  // Plain fallback at the largest available width.
  const largest = widths[widths.length - 1];
  const fallback = path.join(OUT_DIR, `${name}.webp`);
  await sharp(abs).resize({ width: largest }).webp({ quality: QUALITY }).toFile(fallback);
  after += (await stat(fallback)).size;

  manifest[name] = {
    src: `/images/${name}.webp`,
    width: largest,
    // Height at the fallback width, preserving the source aspect ratio.
    height: Math.round((srcH / srcW) * largest),
    srcSet: variants.map((v) => `${v.src} ${v.width}w`).join(", "),
  };

  console.log(`${file}  ${srcW}x${srcH}  ->  ${widths.length + 1} webp`);
}

const ts = `/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run \`npm run images\` after changing anything in public/images.
 *
 * Carries real intrinsic dimensions so components can reserve layout space and
 * avoid cumulative layout shift.
 */
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  srcSet: string;
};

export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageAsset>;

export type ImageName = keyof typeof images;
`;

await writeFile("src/lib/images.ts", ts, "utf8");

// Report like-for-like. Summing every generated width against one original is
// meaningless — a browser downloads exactly one width per image.
const mb = (n) => (n / 1024 / 1024).toFixed(2) + "MB";
let widest = 0;
let narrowest = 0;
for (const name of Object.keys(manifest)) {
  widest += (await stat(path.join(OUT_DIR, `${name}.webp`))).size;
  const small = path.join(OUT_DIR, `${name}-${WIDTHS[0]}.webp`);
  try {
    narrowest += (await stat(small)).size;
  } catch {
    narrowest += (await stat(path.join(OUT_DIR, `${name}.webp`))).size;
  }
}
const pct = (n) => Math.round((1 - n / before) * 100);

console.log(
  `\nper-page image weight:\n` +
    `  original JPEG   ${mb(before)}\n` +
    `  desktop (widest) ${mb(widest)}  (${pct(widest)}% smaller)\n` +
    `  mobile (${WIDTHS[0]}w)     ${mb(narrowest)}  (${pct(narrowest)}% smaller)\n` +
    `  all variants on disk: ${mb(after)}`
);
console.log("wrote src/lib/images.ts");
